### ISSUE TITLE
レイトレ合宿7

### ISSUE THREAD

**Issue by gam0022** [gam0022/redflash#1]
https://sites.google.com/site/raytracingcamp7/

>レンダリング部門の仕様
>60秒以内に自動で終了し、終了時にレンダリング画像をpngで出力してください。

## TODO

- [x] 本番環境での起動チェック
  - [x] [EC2の制限緩和のリクエスト](https://ap-northeast-1.console.aws.amazon.com/ec2/v2/home?region=ap-northeast-1#Limits:)
       - [x] p3.2xlarge    8    26    61 GiB    EBS のみ    3.428USD/時間
       - [x] p3.16xlarge    64    188    488 GiB    EBS のみ    27.424USD/時間
  - [x] [Windowsサーバへのログイン方法の確認](https://aws.amazon.com/jp/getting-started/projects/fileserver/03-1/#)
  - [x] Unityプロジェクト -> 起動はするが 1fps も出ない
  - [x] OptiX公式サンプル
      - [x] OptiX 5
      - [x] OptiX 6
  - [ ] OptixRaymarching そのまま
  - [x] OptixRaymarching 起動オプション変更
  - [x] OptixRaymarching OpenGLとGLUT非依存モード
- [x] optixRaymarching -> redflash にリネーム
- [x] レギューレーション用
   - [x] パスの解決
   - [x] PNG画像の出力
   - [x] 自動終了機能
- [ ] レンダラー機能
  - [x] IBL
  - [x] カメラ制御
  - [x] ポリゴン対応
  - [x] 1回のLaunchで複数サンプリングして高速化
  - [x] 2パスで描画
     - [context.cpp](https://github.com/shocker-0x15/VLR/blob/56999baa013aefcbeaec878f2d08c02b403ddcbf/libVLR/context.cpp#L559-L561)
     - [convert_to_rgb.cu](https://github.com/shocker-0x15/VLR/blob/a313c7a7b47698c33299bb30404d987382cc1573/libVLR/GPU_kernels/convert_to_rgb.cu)
      - [path_tracing.cu](https://github.com/shocker-0x15/VLR/blob/a313c7a7b47698c33299bb30404d987382cc1573/libVLR/GPU_kernels/path_tracing.cu)
  - [x] トーンマッピング
  - [x] Sphereの光源
  - [x] GGX
  - [x] [デノイズ検証](https://github.com/gam0022/redflash/blob/master/optixDenoiser/optixDenoiser.cpp)
  - [ ] DOF
  - [ ] imgui
    - https://github.com/ocornut/imgui/tree/master/examples/example_glut_opengl2
    - [ ] DOF
    - [ ] カメラの位置
  - [ ] カメラの情報をJSONに保存と読み込み
- [x] 外部発信
   - [x] リポジトリ公開
   - [x] ブログ執筆

**Comment by gam0022** [comment]
ブログの記事を書いたので、一旦完了
https://twitter.com/gam0022/status/1174105698503774208
