### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by gam0022** [gam0022/redflash#36]
- [x] マルチGPU環境への対応 https://github.com/gam0022/redflash/pull/40
- [ ] DOF
- [ ] imgui導入
- [ ] CallableProgramID によるリファクタリング
  - [x] BSDF / BTDF https://github.com/gam0022/redflash/pull/41
  - [ ] ライトサンプリング
  - [ ] 距離関数
- [ ] カメラを動かし始めた1フレーム目は低解像度にする
- [ ] redflash.cpp の分割
- [ ] シーン編集機能
